---
# tasks file for docker
- name: install docker
  yum:
    name: docker
    state: present
- name: docker start and enable
  service:
    name: docker
    state: started
    enabled: true
- name: add ec2-user to docker group
  group:
    name: docker
    state: present


